/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class JsEdgePageResult {
  get items(): Array<JsEdgeRecord>
  get nextCursor(): number | null
}

/**
 * Edge record: eager primitives, lazy props. Props are Arc-shared so
 * container getters (page results, subgraph) avoid cloning the BTreeMap.
 */
export declare class JsEdgeRecord {
  get id(): number
  get from(): number
  get to(): number
  get typeId(): number
  get props(): Record<string, any>
  get createdAt(): number
  get updatedAt(): number
  get weight(): number
  get validFrom(): number
  get validTo(): number
}

export declare class JsNeighborBatchEntry {
  get queryNodeId(): number
  /** Lazy neighbor list for this batch entry. */
  get neighbors(): JsNeighborList
}

/**
 * Lazy sequence wrapper around neighbor entries. Data stays in Rust;
 * individual fields are only converted to JS values when accessed via
 * indexed methods. One V8 allocation regardless of result set size.
 * Arc-wrapped so parent containers (batch entries, page results) share
 * data instead of cloning the full vec on every getter access.
 */
export declare class JsNeighborList {
  get length(): number
  nodeId(index: number): number
  edgeId(index: number): number
  edgeTypeId(index: number): number
  weight(index: number): number
  validFrom(index: number): number
  validTo(index: number): number
  /** Get a single entry as a plain object with all fields materialized. */
  get(index: number): JsNeighborEntry
  /** Materialize all entries as an array of plain objects. */
  toArray(): Array<JsNeighborEntry>
}

export declare class JsNeighborPageResult {
  /** Lazy neighbor list for this page. */
  get items(): JsNeighborList
  get nextCursor(): number | null
}

export declare class JsNodePageResult {
  get items(): Array<JsNodeRecord>
  get nextCursor(): number | null
}

/**
 * Node record: eager primitives, lazy props. Props are Arc-shared so
 * container getters (page results, subgraph) avoid cloning the BTreeMap.
 */
export declare class JsNodeRecord {
  get id(): number
  get typeId(): number
  get key(): string
  get props(): Record<string, any>
  get createdAt(): number
  get updatedAt(): number
  get weight(): number
}

export declare class JsSubgraphResult {
  get nodes(): Array<JsNodeRecord>
  get edges(): Array<JsEdgeRecord>
}

export declare class OverGraph {
  static open(path: string, options?: JsDbOptions | undefined | null): OverGraph
  close(options?: JsCloseOptions | undefined | null): void
  upsertNode(typeId: number, key: string, options?: JsUpsertNodeOptions | undefined | null): number
  upsertEdge(from: number, to: number, typeId: number, options?: JsUpsertEdgeOptions | undefined | null): number
  batchUpsertNodes(nodes: Array<JsNodeInput>): Float64Array
  batchUpsertEdges(edges: Array<JsEdgeInput>): Float64Array
  /**
   * Batch upsert nodes from a packed binary Buffer. See `packNodeBatch()` in JS.
   *
   * Binary format (little-endian):
   *   [count: u32]
   *   per node:
   *     [type_id: u32][weight: f32][key_len: u16][key: utf8][props_len: u32][props: json utf8]
   */
  batchUpsertNodesBinary(buffer: Buffer): Float64Array
  /**
   * Batch upsert edges from a packed binary Buffer. See `packEdgeBatch()` in JS.
   *
   * Binary format (little-endian):
   *   [count: u32]
   *   per edge:
   *     [from: u64][to: u64][type_id: u32][weight: f32]
   *     [valid_from: i64][valid_to: i64][props_len: u32][props: json utf8]
   */
  batchUpsertEdgesBinary(buffer: Buffer): Float64Array
  getNode(id: number): JsNodeRecord | null
  getEdge(id: number): JsEdgeRecord | null
  getNodeByKey(typeId: number, key: string): JsNodeRecord | null
  getEdgeByTriple(from: number, to: number, typeId: number): JsEdgeRecord | null
  getNodes(ids: Array<number>): Array<JsNodeRecord | undefined | null>
  getNodesByKeys(keys: Array<JsKeyQuery>): Array<JsNodeRecord | undefined | null>
  getEdges(ids: Array<number>): Array<JsEdgeRecord | undefined | null>
  deleteNode(id: number): void
  deleteEdge(id: number): void
  invalidateEdge(id: number, validTo: number): JsEdgeRecord | null
  graphPatch(patch: JsGraphPatch): JsPatchResult
  prune(policy: JsPrunePolicy): JsPruneResult
  setPrunePolicy(name: string, policy: JsPrunePolicy): void
  removePrunePolicy(name: string): boolean
  listPrunePolicies(): Array<JsNamedPrunePolicy>
  setPrunePolicyAsync(name: string, policy: JsPrunePolicy): Promise<void>
  removePrunePolicyAsync(name: string): Promise<boolean>
  listPrunePoliciesAsync(): Promise<Array<JsNamedPrunePolicy>>
  neighbors(nodeId: number, options?: JsNeighborsOptions | undefined | null): JsNeighborList
  traverse(startNodeId: number, maxDepth: number, options?: JsTraverseOptions | undefined | null): JsTraversalPageResult
  topKNeighbors(nodeId: number, k: number, options?: JsTopKNeighborsOptions | undefined | null): JsNeighborList
  extractSubgraph(startNodeId: number, maxDepth: number, options?: JsExtractSubgraphOptions | undefined | null): JsSubgraphResult
  /**
   * Batch neighbor query: fetch neighbors for multiple nodes in one call.
   * Returns an array of entries, each mapping a query node to its neighbors.
   */
  neighborsBatch(nodeIds: Array<number>, options?: JsNeighborsBatchOptions | undefined | null): Array<JsNeighborBatchEntry>
  degree(nodeId: number, options?: JsDegreeOptions | undefined | null): number
  sumEdgeWeights(nodeId: number, options?: JsSumEdgeWeightsOptions | undefined | null): number
  avgEdgeWeight(nodeId: number, options?: JsAvgEdgeWeightOptions | undefined | null): number | null
  degrees(nodeIds: Array<number>, options?: JsDegreesOptions | undefined | null): Array<JsDegreeBatchEntry>
  shortestPath(from: number, to: number, options?: JsShortestPathOptions | undefined | null): JsShortestPath | null
  isConnected(from: number, to: number, options?: JsIsConnectedOptions | undefined | null): boolean
  allShortestPaths(from: number, to: number, options?: JsAllShortestPathsOptions | undefined | null): Array<JsShortestPath>
  findNodes(typeId: number, propKey: string, propValue: any): Float64Array
  /** Return all node IDs of a given type (unpaged). */
  nodesByType(typeId: number): Float64Array
  /** Return all edge IDs of a given type (unpaged). */
  edgesByType(typeId: number): Float64Array
  getNodesByType(typeId: number): Array<JsNodeRecord>
  getEdgesByType(typeId: number): Array<JsEdgeRecord>
  countNodesByType(typeId: number): number
  countEdgesByType(typeId: number): number
  nodesByTypePaged(typeId: number, limit?: number | undefined | null, after?: number | undefined | null): JsIdPageResult
  edgesByTypePaged(typeId: number, limit?: number | undefined | null, after?: number | undefined | null): JsIdPageResult
  getNodesByTypePaged(typeId: number, limit?: number | undefined | null, after?: number | undefined | null): JsNodePageResult
  getEdgesByTypePaged(typeId: number, limit?: number | undefined | null, after?: number | undefined | null): JsEdgePageResult
  findNodesPaged(typeId: number, propKey: string, propValue: any, options?: JsFindNodesPagedOptions | undefined | null): JsIdPageResult
  findNodesByTimeRange(typeId: number, fromMs: number, toMs: number): Float64Array
  findNodesByTimeRangePaged(typeId: number, fromMs: number, toMs: number, options?: JsFindNodesByTimeRangePagedOptions | undefined | null): JsIdPageResult
  personalizedPagerank(seedNodeIds: Array<number>, options?: JsPersonalizedPagerankOptions | undefined | null): JsPprResult
  exportAdjacency(options?: JsExportOptions | undefined | null): JsAdjacencyExport
  neighborsPaged(nodeId: number, options?: JsNeighborsPagedOptions | undefined | null): JsNeighborPageResult
  connectedComponents(options?: JsConnectedComponentsOptions | undefined | null): Array<JsComponentEntry>
  componentOf(nodeId: number, options?: JsComponentOfOptions | undefined | null): Float64Array
  vectorSearch(mode: string, options: JsVectorSearchOptions): Array<JsVectorHit>
  /**
   * Force an immediate WAL fsync. In GroupCommit mode, blocks until all
   * buffered data is durable. In Immediate mode, this is a no-op.
   */
  sync(): void
  flush(): void
  ingestMode(): void
  endIngest(): JsCompactionStats | null
  compact(): JsCompactionStats | null
  /**
   * Compact with a progress callback. The callback receives a progress object
   * and should return `true` to continue or `false` to cancel.
   * Runs synchronously. Blocks the event loop.
   */
  compactWithProgress(callback: (progress: JsCompactionProgress) => boolean): JsCompactionStats | null
  stats(): JsDbStats
  closeAsync(options?: JsCloseOptions | undefined | null): Promise<void>
  statsAsync(): Promise<JsDbStats>
  upsertNodeAsync(typeId: number, key: string, options?: JsUpsertNodeOptions | undefined | null): Promise<number>
  upsertEdgeAsync(from: number, to: number, typeId: number, options?: JsUpsertEdgeOptions | undefined | null): Promise<number>
  batchUpsertNodesAsync(nodes: Array<JsNodeInput>): Promise<Float64Array>
  batchUpsertEdgesAsync(edges: Array<JsEdgeInput>): Promise<Float64Array>
  batchUpsertNodesBinaryAsync(buffer: Buffer): Promise<Float64Array>
  batchUpsertEdgesBinaryAsync(buffer: Buffer): Promise<Float64Array>
  getNodeAsync(id: number): Promise<JsNodeRecord | null>
  getEdgeAsync(id: number): Promise<JsEdgeRecord | null>
  getNodeByKeyAsync(typeId: number, key: string): Promise<JsNodeRecord | null>
  getEdgeByTripleAsync(from: number, to: number, typeId: number): Promise<JsEdgeRecord | null>
  getNodesAsync(ids: Array<number>): Promise<Array<JsNodeRecord | null>>
  getNodesByKeysAsync(keys: Array<JsKeyQuery>): Promise<Array<JsNodeRecord | null>>
  getEdgesAsync(ids: Array<number>): Promise<Array<JsEdgeRecord | null>>
  deleteNodeAsync(id: number): Promise<void>
  deleteEdgeAsync(id: number): Promise<void>
  invalidateEdgeAsync(id: number, validTo: number): Promise<JsEdgeRecord | null>
  graphPatchAsync(patch: JsGraphPatch): Promise<JsPatchResult>
  pruneAsync(policy: JsPrunePolicy): Promise<JsPruneResult>
  neighborsAsync(nodeId: number, options?: JsNeighborsOptions | undefined | null): Promise<JsNeighborList>
  traverseAsync(startNodeId: number, maxDepth: number, options?: JsTraverseOptions | undefined | null): Promise<JsTraversalPageResult>
  topKNeighborsAsync(nodeId: number, k: number, options?: JsTopKNeighborsOptions | undefined | null): Promise<JsNeighborList>
  extractSubgraphAsync(startNodeId: number, maxDepth: number, options?: JsExtractSubgraphOptions | undefined | null): Promise<JsSubgraphResult>
  findNodesAsync(typeId: number, propKey: string, propValue: any): Promise<Float64Array>
  getNodesByTypeAsync(typeId: number): Promise<Array<JsNodeRecord>>
  getEdgesByTypeAsync(typeId: number): Promise<Array<JsEdgeRecord>>
  countNodesByTypeAsync(typeId: number): Promise<number>
  countEdgesByTypeAsync(typeId: number): Promise<number>
  nodesByTypeAsync(typeId: number): Promise<Float64Array>
  edgesByTypeAsync(typeId: number): Promise<Float64Array>
  neighborsBatchAsync(nodeIds: Array<number>, options?: JsNeighborsBatchOptions | undefined | null): Promise<Array<JsNeighborBatchEntry>>
  degreeAsync(nodeId: number, options?: JsDegreeOptions | undefined | null): Promise<number>
  sumEdgeWeightsAsync(nodeId: number, options?: JsSumEdgeWeightsOptions | undefined | null): Promise<number>
  avgEdgeWeightAsync(nodeId: number, options?: JsAvgEdgeWeightOptions | undefined | null): Promise<number | null>
  degreesAsync(nodeIds: Array<number>, options?: JsDegreesOptions | undefined | null): Promise<Array<JsDegreeBatchEntry>>
  shortestPathAsync(from: number, to: number, options?: JsShortestPathOptions | undefined | null): Promise<JsShortestPath | null>
  isConnectedAsync(from: number, to: number, options?: JsIsConnectedOptions | undefined | null): Promise<boolean>
  allShortestPathsAsync(from: number, to: number, options?: JsAllShortestPathsOptions | undefined | null): Promise<Array<JsShortestPath>>
  nodesByTypePagedAsync(typeId: number, limit?: number | undefined | null, after?: number | undefined | null): Promise<JsIdPageResult>
  edgesByTypePagedAsync(typeId: number, limit?: number | undefined | null, after?: number | undefined | null): Promise<JsIdPageResult>
  getNodesByTypePagedAsync(typeId: number, limit?: number | undefined | null, after?: number | undefined | null): Promise<JsNodePageResult>
  getEdgesByTypePagedAsync(typeId: number, limit?: number | undefined | null, after?: number | undefined | null): Promise<JsEdgePageResult>
  findNodesPagedAsync(typeId: number, propKey: string, propValue: any, options?: JsFindNodesPagedOptions | undefined | null): Promise<JsIdPageResult>
  findNodesByTimeRangeAsync(typeId: number, fromMs: number, toMs: number): Promise<Float64Array>
  findNodesByTimeRangePagedAsync(typeId: number, fromMs: number, toMs: number, options?: JsFindNodesByTimeRangePagedOptions | undefined | null): Promise<JsIdPageResult>
  personalizedPagerankAsync(seedNodeIds: Array<number>, options?: JsPersonalizedPagerankOptions | undefined | null): Promise<JsPprResult>
  exportAdjacencyAsync(options?: JsExportOptions | undefined | null): Promise<JsAdjacencyExport>
  neighborsPagedAsync(nodeId: number, options?: JsNeighborsPagedOptions | undefined | null): Promise<JsNeighborPageResult>
  connectedComponentsAsync(options?: JsConnectedComponentsOptions | undefined | null): Promise<Array<JsComponentEntry>>
  componentOfAsync(nodeId: number, options?: JsComponentOfOptions | undefined | null): Promise<Float64Array>
  vectorSearchAsync(mode: string, options: JsVectorSearchOptions): Promise<Array<JsVectorHit>>
  syncAsync(): Promise<void>
  flushAsync(): Promise<void>
  ingestModeAsync(): Promise<void>
  endIngestAsync(): Promise<JsCompactionStats | null>
  compactAsync(): Promise<JsCompactionStats | null>
  /**
   * Async compaction with a fire-and-forget progress callback.
   * The callback receives progress updates but cannot cancel compaction (unlike the sync version).
   * Note: the database write lock is held for the entire compaction, so other operations on this
   * instance will block until compaction completes. The JS event loop remains responsive.
   */
  compactWithProgressAsync(callback: (progress: JsCompactionProgress) => void): Promise<JsCompactionStats | null>
}

export interface JsAdjacencyExport {
  nodeIds: Float64Array
  edgeFrom: Float64Array
  edgeTo: Float64Array
  edgeTypeIds: Uint32Array
  edgeWeights?: Float64Array
}

export interface JsAllShortestPathsOptions {
  direction?: string
  typeFilter?: Array<number>
  weightField?: string
  atEpoch?: number
  maxDepth?: number
  maxCost?: number
  maxPaths?: number
}

export interface JsAvgEdgeWeightOptions {
  direction?: string
  typeFilter?: Array<number>
  atEpoch?: number
}

export interface JsCloseOptions {
  /** If true, cancel any in-progress background compaction instead of waiting. */
  force?: boolean
}

export interface JsCompactionProgress {
  phase: string
  segmentsProcessed: number
  totalSegments: number
  recordsProcessed: number
  totalRecords: number
}

export interface JsCompactionStats {
  segmentsMerged: number
  nodesKept: number
  nodesRemoved: number
  edgesKept: number
  edgesRemoved: number
  durationMs: number
  outputSegmentId: number
  /** Number of nodes auto-pruned by registered compaction policies. */
  nodesAutoPruned: number
  /** Number of edges cascade-dropped due to auto-pruned nodes. */
  edgesAutoPruned: number
}

export interface JsComponentEntry {
  nodeId: number
  componentId: number
}

export interface JsComponentOfOptions {
  edgeTypeFilter?: Array<number>
  nodeTypeFilter?: Array<number>
  atEpoch?: number
}

export interface JsConnectedComponentsOptions {
  edgeTypeFilter?: Array<number>
  nodeTypeFilter?: Array<number>
  atEpoch?: number
}

export interface JsDbOptions {
  createIfMissing?: boolean
  edgeUniqueness?: boolean
  memtableFlushThreshold?: number
  /** Trigger compaction automatically after this many flushes. Default 5, 0 = disabled. */
  compactAfterNFlushes?: number
  denseVector?: JsDenseVectorConfig
  /** WAL sync mode: 'immediate' or 'group-commit' (default). */
  walSyncMode?: string
  /** Group commit sync interval in milliseconds. Default: 10. */
  groupCommitIntervalMs?: number
  /** Hard cap on memtable size in bytes. Writes trigger a flush when exceeded. 0 = disabled. */
  memtableHardCapBytes?: number
  /**
   * Maximum number of immutable memtables pending flush before writers block.
   * Default: 4. Set to 0 to disable immutable count backpressure.
   */
  maxImmutableMemtables?: number
}

export interface JsDbStats {
  /** Bytes buffered in WAL but not yet fsynced. Always 0 in immediate mode. */
  pendingWalBytes: number
  /** Number of on-disk segments. */
  segmentCount: number
  /** Node tombstones in the memtable. */
  nodeTombstoneCount: number
  /** Edge tombstones in the memtable. */
  edgeTombstoneCount: number
  /** Timestamp (ms since epoch) of last completed compaction, or null. */
  lastCompactionMs?: number
  /** WAL sync mode: "immediate" or "group-commit". */
  walSyncMode: string
  /** Estimated bytes in the active (mutable) memtable. */
  activeMemtableBytes: number
  /** Estimated bytes across all immutable memtables pending flush. */
  immutableMemtableBytes: number
  /** Number of immutable memtables pending flush. */
  immutableMemtableCount: number
  /** Number of flush operations currently in flight. */
  pendingFlushCount: number
  /** The WAL generation ID currently being written to. */
  activeWalGenerationId: number
  /** The oldest WAL generation ID still retained for recovery. */
  oldestRetainedWalGenerationId: number
}

export interface JsDegreeBatchEntry {
  nodeId: number
  degree: number
}

export interface JsDegreeOptions {
  direction?: string
  typeFilter?: Array<number>
  atEpoch?: number
}

export interface JsDegreesOptions {
  direction?: string
  typeFilter?: Array<number>
  atEpoch?: number
}

export interface JsDenseVectorConfig {
  dimension: number
  metric?: string
}

export interface JsEdgeInput {
  from: number
  to: number
  typeId: number
  props?: Record<string, any>
  weight?: number
  validFrom?: number
  validTo?: number
}

export interface JsEdgeInvalidation {
  edgeId: number
  validTo: number
}

export interface JsExportOptions {
  nodeTypeFilter?: Array<number>
  edgeTypeFilter?: Array<number>
  includeWeights?: boolean
}

export interface JsExtractSubgraphOptions {
  direction?: string
  edgeTypeFilter?: Array<number>
  atEpoch?: number
}

export interface JsFindNodesByTimeRangePagedOptions {
  limit?: number
  after?: number
}

export interface JsFindNodesPagedOptions {
  limit?: number
  after?: number
}

export interface JsGraphPatch {
  upsertNodes?: Array<JsNodeInput>
  upsertEdges?: Array<JsEdgeInput>
  invalidateEdges?: Array<JsEdgeInvalidation>
  deleteNodeIds?: Array<number>
  deleteEdgeIds?: Array<number>
}

export interface JsIdPageResult {
  items: Float64Array
  nextCursor?: number
}

export interface JsIsConnectedOptions {
  direction?: string
  typeFilter?: Array<number>
  atEpoch?: number
  maxDepth?: number
}

export interface JsKeyQuery {
  typeId: number
  key: string
}

export interface JsNamedPrunePolicy {
  name: string
  policy: JsPrunePolicy
}

/**
 * A single neighbor entry as a plain JS object.
 * Used by `JsNeighborList.get(i)` and `JsNeighborList.toArray()`.
 */
export interface JsNeighborEntry {
  nodeId: number
  edgeId: number
  edgeTypeId: number
  weight: number
  validFrom: number
  validTo: number
}

export interface JsNeighborsBatchOptions {
  direction?: string
  typeFilter?: Array<number>
  atEpoch?: number
  decayLambda?: number
}

export interface JsNeighborsOptions {
  direction?: string
  typeFilter?: Array<number>
  limit?: number
  atEpoch?: number
  decayLambda?: number
}

export interface JsNeighborsPagedOptions {
  direction?: string
  typeFilter?: Array<number>
  limit?: number
  after?: number
  atEpoch?: number
  decayLambda?: number
}

export interface JsNodeInput {
  typeId: number
  key: string
  props?: Record<string, any>
  weight?: number
  denseVector?: Array<number>
  sparseVector?: Array<JsSparseEntry>
}

export interface JsPatchResult {
  nodeIds: Float64Array
  edgeIds: Float64Array
}

export interface JsPersonalizedPagerankOptions {
  dampingFactor?: number
  maxIterations?: number
  epsilon?: number
  edgeTypeFilter?: Array<number>
  maxResults?: number
}

export interface JsPprResult {
  nodeIds: Float64Array
  scores: Float64Array
  iterations: number
  converged: boolean
}

export interface JsPrunePolicy {
  /** Prune nodes older than this many milliseconds. Optional. */
  maxAgeMs?: number
  /** Prune nodes with weight <= this threshold. Optional. */
  maxWeight?: number
  /** Scope to a single node type. Optional. */
  typeId?: number
}

export interface JsPruneResult {
  /** Number of nodes pruned. */
  nodesPruned: number
  /** Number of edges cascade-deleted. */
  edgesPruned: number
}

export interface JsShortestPath {
  nodes: Array<number>
  edges: Array<number>
  totalCost: number
}

export interface JsShortestPathOptions {
  direction?: string
  typeFilter?: Array<number>
  weightField?: string
  atEpoch?: number
  maxDepth?: number
  maxCost?: number
}

export interface JsSparseEntry {
  dimension: number
  value: number
}

export interface JsSumEdgeWeightsOptions {
  direction?: string
  typeFilter?: Array<number>
  atEpoch?: number
}

export interface JsTopKNeighborsOptions {
  direction?: string
  typeFilter?: Array<number>
  scoring?: string
  decayLambda?: number
  atEpoch?: number
}

export interface JsTraversalCursor {
  depth: number
  lastNodeId: number
}

export interface JsTraversalHit {
  nodeId: number
  depth: number
  viaEdgeId?: number
  score?: number
}

export interface JsTraversalPageResult {
  items: Array<JsTraversalHit>
  nextCursor?: JsTraversalCursor
}

export interface JsTraverseOptions {
  minDepth?: number
  direction?: string
  edgeTypeFilter?: Array<number>
  nodeTypeFilter?: Array<number>
  atEpoch?: number
  decayLambda?: number
  limit?: number
  cursor?: JsTraversalCursor
}

export interface JsUpsertEdgeOptions {
  props?: Record<string, any>
  weight?: number
  validFrom?: number
  validTo?: number
}

export interface JsUpsertNodeOptions {
  props?: Record<string, any>
  weight?: number
  denseVector?: Array<number>
  sparseVector?: Array<JsSparseEntry>
}

export interface JsVectorHit {
  nodeId: number
  score: number
}

export interface JsVectorSearchOptions {
  k: number
  denseQuery?: Array<number>
  sparseQuery?: Array<JsSparseEntry>
  typeFilter?: Array<number>
  efSearch?: number
  scope?: JsVectorSearchScope
  denseWeight?: number
  sparseWeight?: number
  fusionMode?: string
}

export interface JsVectorSearchScope {
  startNodeId: number
  maxDepth: number
  direction?: string
  edgeTypeFilter?: Array<number>
  atEpoch?: number
}
